sudo: required
dist: trusty

language: csharp

solution: Srclib.Nuget.sln

before_install:
  - cd /tmp
  - wget http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
  - tar -xvf libunwind-1.1.tar.gz
  - cd libunwind-1.1 && ./configure && make > /dev/null 2>&1
  - sudo make install
  - cd /tmp
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - sudo apt-get install -y gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev
  - dnvm upgrade -r coreclr
  - which dnu
  - mkdir -p $HOME/bin
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph
  - export PATH=$PATH:$HOME/bin
  - curl -Lo $HOME/bin/srclib.gz https://srclib-release.s3.amazonaws.com/srclib/0.2.0/linux-amd64/srclib.gz 
  - gunzip -c $HOME/bin/srclib.gz > $HOME/bin/srclib
  - sudo chmod +x $HOME/bin/srclib
  - ln -s $TRAVIS_BUILD_DIR $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-csharp
  - srclib toolchain list
  - cd $TRAVIS_BUILD_DIR
  - dnu restore Srclib.Nuget/project.json
  - srclib -v test

install:
  - pwd

script:
  - pwd
  - dnu restore Srclib.Nuget/project.json
  - srclib -v test
 
